# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodDriver' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodDriver
    pod 'MBProgressHUD'
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'IQKeyboardManagerSwift'
    pod 'SDWebImage'
    pod 'ImageSlideshow'
    pod 'SlideMenuControllerSwift'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Localize-Swift', '~> 2.0'
    pod 'LanguageManager-iOS'

  target 'FoodDriverTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodDriverUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
